// <auto-generated />
namespace ERP.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class INITDBCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INITDBCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201804111800088_INITDBCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
